version: "3.1"
services:
  react:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: abc-gui
    volumes:
      - "/app/node_modules"
    expose:
      - 8080
    ports:
      - "8080:8080"
    stdin_open: true
